# YAML syntax quick references:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings

title: Liberty Ski Patrol SOP Guide
description: >- 
  This website is intended primarily for the use of members of the 
  Liberty Mountain Ski Patrol and contains a collection of information, procedures, and tools
  to facilitate quick and easy reference.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://drewnielson.github.io/SkiPatrolSOPs/" # the base hostname & protocol for your site, e.g. http://example.com

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Lift Evac
    url: /liftevac/
  - name: Lost Child
    url: /lostchild/
  - name: Open
    url: /open/
  - name: Close
    url: /close/
  - name: Mass Casualty
    url: /mci/
  - name: Ski Swap Bookmarklets
    url: /swap-fee/

collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - page-templates/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - .markdownlint.json
